[tool.poetry]
name = "student-teacher"
version = "0.1.0"
description = ""
authors = ["04116"]

[tool.poetry.dependencies]
python = "^3.11"
duckdb = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
